### ISSUE TITLE
Calibration curves for 14C ages

### ISSUE THREAD

**Issue by guiguerin** [R-Lum/BayLum#4]
### Expected behaviour: 
Calibration curves for radiocarbon in the package should give calibrated ages in ka (the unit of OSL ages)

### Observed behaviour: 
Calibrated ages are given in years.

### Running mini example

```r
library(BayLum)

```

**Comment by RLumSK** [comment]
Please clarify, which function is affected?

**Comment by guiguerin** [comment]
The two functions needing the calibration curves - AgeC14_Computation  
and Age_OSLC14. But the objects that need to be changed are  
AtmosphericNorth_CalC14, AtmosphericSouth_CalC14 and Marine_CalC14: in  
these objects, all values in the column CAL.BP (first column) should  
be divided by 1000.

I hope it's clear enough, otherwise just let me know!
Guillaume


Sebastian Kreutzer <notifications@github.com> a écrit&nbsp;:
