### ISSUE TITLE
Labels for figures produced by MCMC_plot

### ISSUE THREAD

**Issue by guiguerin** [R-Lum/BayLum#5]
### Expected behaviour
There should be proper titles for the axes of the figures produced by the function MCMC_plot (or one Age computation function, which calls MCMC_plot). For the chains (left panel), xlab = iteration, ylab = Age (ka) for the top row, D (Gy) for the middle row, sD (Gy) for the bottom row.

### Observed behaviour
When running the function MCMC_plot or one Age computation function, several problems appear in the figures showing the MCMC (unnecessary titles appear, but no axis title appears). 

### Running mini example

```r
library(BayLum)
load(DATA3)
priorage <- c(10,60) 
Age <- Age_Computation(
  DATA = DATA3,
  SampleName = "FER1",
  PriorAge = priorage,
  Iter = 100,
  quiet = FALSE)
```

**Comment by guiguerin** [comment]
On top of this problem, the axis range for each MCMC plot and each posterior density plot is set based on the range of values for the first chain. When the other two chains diverge from the first, the corresponding values are out of range and thus don't appear on the graph!

A solution to this problem could be offered by the function matplot.

**Comment by RLumSK** [comment]
This takes a little bit more time. I discovered some odd things which have to be fixed first: 

- The function states that an`mcmc.list` is requested, however, if some is provided it crashes 
- The object treated is not an`mcmc` object

**Comment by RLumSK** [comment]
I replaced the function with a new one, there was no other way.  Should work now, please check

**Comment by RLumSK** [comment]
Ok, I guess this is ok now.
