### ISSUE TITLE
Waring: closing unsued connection

### ISSUE THREAD

**Issue by guiguerin** [R-Lum/BayLum#7]
### Expected behaviour
There should be no warning when running the function Generate_DataFile

### Observed behaviour
One gets the following warning when running the function Generate_DatFile: 

```
## Warning: fermeture de la connexion inutilisée 5 (E:/Documents Guillaume/
## Stats/BayLum/Ferrassie/FER1/bin.BIN)
```

Note: no running mini example as there is no bin file included in the package

### Running mini example

```r
library(BayLum)

```

**Comment by RLumSK** [comment]
This is not a bug but happens when the import before crashed and connections are still open. Apart from it, the new version of the R package `Luminescence` (0.8.0, release soon), will take care of such things and close the connections automatically in case an error occurred.
