### ISSUE TITLE
AgeC14_Computation() - cal. C-14 plot shows no data

### ISSUE THREAD

**Issue by RLumSK** [R-Lum/BayLum#9]
### Expected behaviour

The C-14 ages vs ages plot shows something. 

### Observed behaviour

Only the plot frame is shown, the values are off-scale.

### Running mini example

```r
library(BayLum)
## Load data
data(DATA_C14,envir = environment())
C14Cal <- DATA_C14$C14[,1]
SigmaC14Cal <- DATA_C14$C14[,2]
Names <- DATA_C14$Names
nb_sample <- length(Names)

## Age computation of samples without stratigraphic relations
Age <- AgeC14_Computation(
 Data_C14Cal = C14Cal,
 Data_SigmaC14Cal = SigmaC14Cal,
 SampleNames = Names,
 Nb_sample = nb_sample,
 PriorAge = rep(c(20,60),nb_sample),
 Iter = 500,
 quiet = TRUE)
```

### Comments

The C-14 dataset ( `data(DATA_C14,envir = environment())`) has its unit in years ('a'), but the plot expects kyears ('ka'). It appears that the values are never re-calculated. The question remains whether the dataset should be changed or the function. Further, I did not test for side effects, but it appears that internally the dataset is never re-calculated into 'ka', means, it is unlikely that the calculation output is overall correct . To be tested. Other functions might be affected as well, I did not test it.

**Comment by philippe-a** [comment]
the code has been modified to draw the curve in kA.
